/*
 * generated by Xtext 2.12.0
 */
package at.ac.tuwien.big.tsm.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTsmScopeProvider extends DelegatingScopeProvider {
}
