/*
 * generated by Xtext 2.12.0
 */
package at.ac.tuwien.big.tsm.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TsmStandaloneSetup extends TsmStandaloneSetupGenerated {

	def static void doSetup() {
		new TsmStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
