/*
 * generated by Xtext 2.12.0
 */
package at.ac.tuwien.big.tsm.xtext.ide

import at.ac.tuwien.big.tsm.xtext.TsmRuntimeModule
import at.ac.tuwien.big.tsm.xtext.TsmStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class TsmIdeSetup extends TsmStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new TsmRuntimeModule, new TsmIdeModule))
	}
	
}
