/*
 * generated by Xtext 2.12.0
 */
package at.ac.tuwien.big.tsm.xtext.ui;

import at.ac.tuwien.big.tsm.xtext.tsm.ui.internal.TsmActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TsmExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TsmActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TsmActivator.getInstance().getInjector(TsmActivator.AT_AC_TUWIEN_BIG_TSM_XTEXT_TSM);
	}
	
}
