/*
 * generated by Xtext 2.12.0
 */
package at.ac.tuwien.big.tsm.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TsmAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("at/ac/tuwien/big/tsm/xtext/parser/antlr/internal/InternalTsm.tokens");
	}
}
